//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripciones
    {
        public int estudianteID { get; set; }
        public Nullable<int> cursoID { get; set; }
    
        public virtual Cursos Cursos { get; set; }
        public virtual Estudiantes Estudiantes { get; set; }
    }
}
